/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gzip.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gzip.pb-c.h"
void   compress__init
                     (Compress         *message)
{
  static Compress init_value = COMPRESS__INIT;
  *message = init_value;
}
size_t compress__get_packed_size
                     (const Compress *message)
{
  assert(message->base.descriptor == &compress__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t compress__pack
                     (const Compress *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &compress__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t compress__pack_to_buffer
                     (const Compress *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &compress__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Compress *
       compress__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Compress *)
     protobuf_c_message_unpack (&compress__descriptor,
                                allocator, len, data);
}
void   compress__free_unpacked
                     (Compress *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &compress__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uncompress__init
                     (Uncompress         *message)
{
  static Uncompress init_value = UNCOMPRESS__INIT;
  *message = init_value;
}
size_t uncompress__get_packed_size
                     (const Uncompress *message)
{
  assert(message->base.descriptor == &uncompress__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uncompress__pack
                     (const Uncompress *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uncompress__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uncompress__pack_to_buffer
                     (const Uncompress *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uncompress__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uncompress *
       uncompress__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uncompress *)
     protobuf_c_message_unpack (&uncompress__descriptor,
                                allocator, len, data);
}
void   uncompress__free_unpacked
                     (Uncompress *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &uncompress__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   return__init
                     (Return         *message)
{
  static Return init_value = RETURN__INIT;
  *message = init_value;
}
size_t return__get_packed_size
                     (const Return *message)
{
  assert(message->base.descriptor == &return__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t return__pack
                     (const Return *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &return__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t return__pack_to_buffer
                     (const Return *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &return__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Return *
       return__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Return *)
     protobuf_c_message_unpack (&return__descriptor,
                                allocator, len, data);
}
void   return__free_unpacked
                     (Return *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &return__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   request__init
                     (Request         *message)
{
  static Request init_value = REQUEST__INIT;
  *message = init_value;
}
size_t request__get_packed_size
                     (const Request *message)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request__pack
                     (const Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request__pack_to_buffer
                     (const Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Request *)
     protobuf_c_message_unpack (&request__descriptor,
                                allocator, len, data);
}
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor compress__field_descriptors[4] =
{
  {
    "fd_in",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Compress, fd_in),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fd_out",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Compress, fd_out),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "original_name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Compress, original_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mtime",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Compress, has_mtime),
    offsetof(Compress, mtime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned compress__field_indices_by_name[] = {
  0,   /* field[0] = fd_in */
  1,   /* field[1] = fd_out */
  3,   /* field[3] = mtime */
  2,   /* field[2] = original_name */
};
static const ProtobufCIntRange compress__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor compress__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Compress",
  "Compress",
  "Compress",
  "",
  sizeof(Compress),
  4,
  compress__field_descriptors,
  compress__field_indices_by_name,
  1,  compress__number_ranges,
  (ProtobufCMessageInit) compress__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor uncompress__field_descriptors[5] =
{
  {
    "fd_in",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Uncompress, fd_in),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fd_out",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Uncompress, fd_out),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filename",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Uncompress, filename),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pre",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Uncompress, pre),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prelen",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Uncompress, has_prelen),
    offsetof(Uncompress, prelen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uncompress__field_indices_by_name[] = {
  0,   /* field[0] = fd_in */
  1,   /* field[1] = fd_out */
  2,   /* field[2] = filename */
  3,   /* field[3] = pre */
  4,   /* field[4] = prelen */
};
static const ProtobufCIntRange uncompress__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor uncompress__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Uncompress",
  "Uncompress",
  "Uncompress",
  "",
  sizeof(Uncompress),
  5,
  uncompress__field_descriptors,
  uncompress__field_indices_by_name,
  1,  uncompress__number_ranges,
  (ProtobufCMessageInit) uncompress__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor return__field_descriptors[2] =
{
  {
    "size",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Return, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Return, bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned return__field_indices_by_name[] = {
  1,   /* field[1] = bytes */
  0,   /* field[0] = size */
};
static const ProtobufCIntRange return__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor return__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Return",
  "Return",
  "Return",
  "",
  sizeof(Return),
  2,
  return__field_descriptors,
  return__field_indices_by_name,
  1,  return__number_ranges,
  (ProtobufCMessageInit) return__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue request__type__enum_values_by_number[2] =
{
  { "COMPRESS", "REQUEST__TYPE__COMPRESS", 1 },
  { "UNCOMPRESS", "REQUEST__TYPE__UNCOMPRESS", 2 },
};
static const ProtobufCIntRange request__type__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex request__type__enum_values_by_name[2] =
{
  { "COMPRESS", 0 },
  { "UNCOMPRESS", 1 },
};
const ProtobufCEnumDescriptor request__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Request.Type",
  "Type",
  "Request__Type",
  "",
  2,
  request__type__enum_values_by_number,
  2,
  request__type__enum_values_by_name,
  1,
  request__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor request__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Request, type),
    &request__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "compress",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Request, compress),
    &compress__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uncompress",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Request, uncompress),
    &uncompress__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__field_indices_by_name[] = {
  1,   /* field[1] = compress */
  0,   /* field[0] = type */
  2,   /* field[2] = uncompress */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request",
  "Request",
  "Request",
  "",
  sizeof(Request),
  3,
  request__field_descriptors,
  request__field_indices_by_name,
  1,  request__number_ranges,
  (ProtobufCMessageInit) request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
