#define BUFLEN		(64 * 1024)

#include "gzip_builder.h" // Generated by flatcc
#undef ns
#define ns(x) FLATBUFFERS_WRAP_NAMESPACE(Gzip, x)

void gz_sandbox(int sock);

off_t gz_compress_wrapper(int in, int out, off_t *gsizep, const char *origname, uint32_t mtime, int sock);
off_t gz_uncompress_wrapper(int in, int out, char *pre, size_t prelen, off_t *gsizep,
	      const char *filename, int sock);

void gz_compress_unwrapper(ns(Compress_table_t) compress, int* fds, int* nonces, int sock);
void gz_uncompress_unwrapper(ns(Uncompress_table_t) uncompress, int* fds, int* nonces, int sock);


void limit_fds(int in, int out);
void send_response( off_t gsizep, off_t bytes, int sock );
